FROM nvcr.io/nvidia/pytorch:21.10-py3

ENV MLFLOW_TRACKING_URI "http://0.0.0.0:5000"
# Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx

# Install python dependencies
COPY conda.yaml .
RUN conda update -y -n base conda
RUN conda env create -f conda.yaml

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
