version: '3'

services:
  myprj:
    build:
      context: .
      dockerfile: Dockerfile_tracking_server
    image: mlflow_tracking_server:latest
    container_name: mlflow_tracking_server
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MYHOST=${MYHOST}
      - BACKEND_URI=${BACKEND_URI}
      - ARTIFACT_URI=${ARTIFACT_URI}
    ports:
      - "8000:5000"
    expose:
      - "5000"
    networks:
      - frontend
      - backend
    command: /bin/bash -c "source activate mlflow_tracking_server && mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_URI} --host ${MYHOST}"
  # nginx:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_nginx
  #   image: mlflow_nginx:latest
  #   container_name: mlflow_nginx
  #   ports:
  #     - "80:80"
  #   networks:
  #     - frontend
  #   depends_on:
  #     - myprj

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
